[package]
name = "lightkeeper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
log = "0.4.0"
env_logger = "0.8.4"
ssh2 = "0.9.3"
serde = "1.0.137"
serde_derive = "1.0.137"
toml = "0.5.5"
chrono = "0.4.0"
oping = "0.4.0"
tabled = "0.6.1"
