[package]
name = "lightkeeper"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "lightkeeper"
path = "src/main.rs"

[dependencies]
oping = "0.4.0"
clap = { version = "4.3.11", features = ["derive"] }
log = "0.4.0"
env_logger = "0.8.4"
ssh2 = "0.9.3"
serde = "1.0.137"
serde_derive = "1.0.137"
serde_yaml = "0.8.24"
serde_json = "1.0.81"
chrono = { version = "0.4.0", features = ["serde"]}
tabled = { version = "0.6.1", features = ["color"] }
owo-colors = "3.4.0"
qmetaobject = "0.2.7"
cstr = "0.2.10"
sha256 = "1.1.1"
strum = "0.24"
strum_macros = "0.24"
ureq = "2.6.2"
rayon = "1.7"

lightkeeper_module = { path = "macros/lightkeeper_module" }
