[package]
name = "lightkeeper"
version = "0.25.0"
edition = "2021"

[[bin]]
name = "lightkeeper"
path = "src/main.rs"

[dependencies]
oping = "0.4.0"
dbus = "0.9.7"
clap = { version = "4.5.16", features = ["derive"] }
log = "0.4.22"
env_logger = "0.11.5"
ssh2 = "0.9.4"
serde = "1.0.200"
serde_derive = "1.0.200"
serde_yaml = "0.9.33"
serde_json = "1.0.116"
chrono = { version = "0.4.38", features = ["serde"]}
qmetaobject = "0.2.10"
cstr = "0.2.12"
sha2 = "0.10.8"
strum = "0.26.3"
strum_macros = "0.26.4"
ureq = "2.10.1"
rayon = "1.10.0"
rand = "0.8.5"
regex = "1.10.6"
rustls = "0.22.4"
rustls-native-certs = "0.7.2"
rustls-pemfile = "2.1.3"
x509-parser = "0.16.0"
base64 = "0.22.1"
hex = "0.4.3"
bincode = "1.3.3"
openssl = { version = "0.10.66", features = ["vendored"] }
# Only for hot reload.
notify = { version = "7.0.0" }

lightkeeper_module = { path = "macros/lightkeeper_module" }

# [dev-dependencies]
# notify = { version = "7.0.0" }

