[package]
name = "lightkeeper"
version = "0.17.4"
edition = "2021"

[[bin]]
name = "lightkeeper"
path = "src/main.rs"

[dependencies]
oping = "0.4.0"
dbus = "0.9.7"
clap = { version = "4.5.4", features = ["derive"] }
log = "0.4.21"
env_logger = "0.11.3"
ssh2 = "0.9.4"
serde = "1.0.200"
serde_derive = "1.0.200"
serde_yaml = "0.9.33"
serde_json = "1.0.116"
chrono = { version = "0.4.38", features = ["serde"]}
qmetaobject = "0.2.10"
cstr = "0.2.12"
sha256 = "1.5.0"
strum = "0.26.2"
strum_macros = "0.26.2"
ureq = "2.9.7"
rayon = "1.10.0"
rand = "0.8.5"
regex = "1.10.4"
base64 = "0.22.1"
hex = "0.4.3"

lightkeeper_module = { path = "macros/lightkeeper_module" }
