authentication:
  username: exampleuser
  password: ""

hosts:
  - name: examplehost1
    address: 10.4.0.2
    monitors:
      - name: uptime
        version: 0.0.1
      - name: ping
        version: 0.0.1
  - name: examplehost2
    fqdn: examplehost2.invalid
    monitors:
      - name: ssh
        version: 0.0.1
        is_critical: true

