preferences:
  use_remote_editor: true
  refresh_hosts_on_start: true
  sudo_remote_editor: false
  remote_text_editor: "/usr/bin/vim"
  text_editor: "/usr/bin/kate"
  terminal: "/usr/bin/konsole"
  terminal_args: ["-e"]

general:
  # Assume hosts are down (or up) until a critical monitor says otherwise.
  default_host_status: "down"

display_options:
  # Group monitors with multiple values into one column (or similar) or display everything separately.
  group_multivalue: true
  category_order: []
  command_order: [
    "logs",
    "docker-inspect", "docker-restart", "docker-shell", "docker-image-remove",
    "reboot", "shutdown",
    "docker-compose-edit", "docker-compose-pull", "docker-compose-up", "docker-compose-play", "docker-compose-stop",
  ]
  collapsible_commands:
    - docker-compose-up
    - docker-compose-pull
    - docker-compose-edit
  categories:
    host:
      priority: 1
    network:
      priority: 2
    systemd:
      priority: 3
    package:
      priority: 4
    docker-compose:
      priority: 5
      icon: "qrc:///main/images/docker"
      color: "#8010a0ee"
    docker-containers:
      priority: 6
      icon: "qrc:///main/images/docker"
      color: "#8010a0ee"
    docker-images:
      priority: 7
      icon: "qrc:///main/images/docker"
      color: "#8010a0ee"
