general:
  # Assume hosts are down (or up) until a critical monitor says otherwise.
  default_host_status: "down"

display_options:
  # Group monitors with multiple values into one column (or similar) or display everything separately.
  group_multivalue: true
  category_order: []
  command_order: ["docker-inspect", "docker-restart", "docker-shell", "docker-image-remove"]

defaults:
  monitors:
    ssh:
      username: exampleuser
      password: ""

hosts:
  test1:
    fqdn: test.domain.invalid
    monitors:
      ping:
        version: 0.0.1
        is_critical: true
  test2:
    address: 10.0.20.2
    monitors:
      ssh:
        version: 0.0.1
        is_critical: true
