preferences:
  use_remote_editor: true
  refresh_hosts_on_start: false
  sudo_remote_editor: true
  remote_text_editor: "/usr/bin/vim"
  text_editor: "/usr/bin/kate"
  terminal: "/usr/bin/konsole"
  terminal_args: ["-e"]

cache_settings:
  enable_cache: false
  provide_initial_value: true
  initial_value_time_to_live: 604800
  prefer_cache: true
  time_to_live: 8400

display_options:
  # Group monitors with multiple values into one column (or similar) or display everything separately.
  group_multivalue: true
  categories:
    host:
      priority: 1
      color: "#80b3825d"
      command_order: ["reboot", "shutdown", "logs"]
      monitor_order: ["uptime", "os", "kernel", "filesystem"]
    storage:
      priority: 2
      color: "#80b3825d"
      command_order: ["linux-lvm-snapshot", "linux-lvm-lvresize", "linux-lvm-lvremove"]
      monitor_order: ["filesystem", "linux-lvm-logical-volume", "linux-lvm-volume-group", "linux-lvm-physical-volume"]
    network:
      priority: 3
      color: "#80b3825d"
      monitor_order: ["ping", "ssh", "interface"]
    systemd:
      priority: 4
      color: "#8030d475"
      command_order: ["systemd-service-stop", "systemd-service-start"]
    package:
      priority: 5
    docker-compose:
      priority: 6
      icon: "qrc:///main/images/docker"
      color: "#8010a0ee"
      command_order: ["docker-compose-edit", "docker-compose-pull", "docker-compose-up", "docker-compose-play", "docker-compose-stop"]
      collapsible_commands: [ "docker-compose-up", "docker-compose-pull", "docker-compose-edit" ]
    docker-containers:
      priority: 7
      icon: "qrc:///main/images/docker"
      color: "#8010a0ee"
    docker-images:
      priority: 8
      icon: "qrc:///main/images/docker"
      color: "#8010a0ee"
      command_order: ["docker-inspect", "docker-restart", "docker-shell", "docker-image-remote-tags", "docker-image-remove"]
