preferences:
  # Refresh all hosts on application start.
  refresh_hosts_on_start: false
  # Some commands allow you to edit a remote file.
  # This can be done directly over a terminal or by temporarily downloading the file for editing locally.
  # If set to true, will launch a terminal for editing directly using a CLI text editor.
  use_remote_editor: true
  # This is the command (or path) to the remote CLI text editor.
  remote_text_editor: "nano"
  # Use sudo when editing remote files?
  sudo_remote_editor: true
  # Likewise, command (or path) to an editor for editing locally.
  # If set to "internal", will use the integrated text editor.
  text_editor: "internal"
  # Some commands may launch a terminal for you. Here you can configure the terminal and parameters.
  # If set to "internal", will use the integrated terminal.
  terminal: "internal"
  terminal_args: [""]

# Caching can provide speed benefits especially if you have many hosts.
# Recommended to be left disabled for now.
cache_settings:
  enable_cache: false
  provide_initial_value: true
  initial_value_time_to_live: 604800
  prefer_cache: true
  time_to_live: 8400

# Control category order, command buttons orders, colors. Defaults should be good.
# NOTE: Currently, you shouldn't manually edit display_options at all.
display_options:
  # Empty means default.
  qtquick_style: ""
  hide_info_notifications: false
  categories:
    host:
      # Priority controls the order of the category tiles. Host should be first.
      priority: 1
      # Color of the label bar.
      color: "#80b3825d"
      # Order of command buttons.
      command_order: ["shell", "reboot", "shutdown", "logs"]
      # Order of monitors.
      monitor_order: ["uptime", "load", "ram", "os", "kernel", "filesystem"]
    nixos:
      priority: 2
      color: "#80b3825d"
      command_order: ["nixos-collectgarbage", "nixos-channel-update", "nixos-rebuild-dryrun", "nixos-rebuild-switch"]
    storage:
      priority: 3
      color: "#80b3825d"
      command_order: ["storage-lvm-lvrefresh", "storage-lvm-snapshot", "storage-lvm-lvresize", "storage-lvm-lvremove"]
      monitor_order: ["filesystem", "storage-lvm-logical-volume", "storage-lvm-volume-group", "storage-lvm-physical-volume"]
    network:
      priority: 4
      color: "#80b3825d"
      monitor_order: ["oping", "ping", "tcp-connect", "ssh", "network-dns", "interface", "network-routes"]
    systemd:
      priority: 5
      color: "#8030d475"
      command_order: ["systemd-service-logs", "systemd-service-stop", "systemd-service-start", "systemd-service-mask", "systemd-service-unmask"]
    package:
      priority: 6
      command_order: ["linux-packages-logs", "linux-packages-clean", "linux-packages-refresh", "linux-packages-update-all"]
    docker-compose:
      priority: 7
      icon: "qrc:///main/images/docker"
      color: "#8010a0ee"
      command_order: ["docker-compose-edit", "docker-compose-start", "docker-compose-stop", "docker-compose-build", "docker-compose-pull", "docker-compose-up", "docker-compose-shell", "docker-compose-logs"]
      collapsible_commands: ["docker-compose-start", "docker-compose-stop", "docker-compose-edit", "docker-compose-build", "docker-compose-pull", "docker-compose-up"]
    docker-containers:
      priority: 8
      icon: "qrc:///main/images/docker"
      color: "#8010a0ee"
    docker-images:
      priority: 9
      icon: "qrc:///main/images/docker"
      color: "#8010a0ee"
      command_order: ["docker-inspect", "docker-restart", "docker-shell", "docker-image-remote-tags", "docker-image-remove"]
