unstable_features = true
reorder_imports = true
imports_layout = "HorizontalVertical"
max_width = 150
newline_style = "Unix"
group_imports = "StdExternalCrate"
control_brace_style = "ClosingNextLine"
binop_separator = "Back"
# attr_fn_like_width = 120
# indent_style = "Visual"
# wrap_comments = true
