unstable_features = true
reorder_imports = true
max_width = 150
newline_style = "Unix"
group_imports = "StdExternalCrate"
control_brace_style = "ClosingNextLine"
# attr_fn_like_width = 120
# indent_style = "Visual"
# wrap_comments = true
