hosts:
  ubuntu2204:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    - systemd-service
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            private_key_path: test-env/ubuntu2204/.vagrant/machines/default/libvirt/private_key
            port: '33332'
      host_settings:
      - use_sudo
  debian11:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    address: 127.0.0.1
    overrides:
      custom_commands:
      - name: Top 10 processes by CPU
        description: ''
        command: ps -eo pid,ppid,user,%cpu,%mem,cmd --sort=-%cpu | head -n 10
      connectors:
        ssh:
          settings:
            private_key_path: test-env/debian11/.vagrant/machines/default/libvirt/private_key
            port: '33303'
      host_settings:
      - use_sudo
  centos8:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            port: '33312'
            private_key_path: test-env/centos8/.vagrant/machines/default/libvirt/private_key
  alpine318:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    - systemd-service
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            private_key_path: test-env/alpine318/.vagrant/machines/default/libvirt/private_key
            port: '33351'
      host_settings:
      - use_sudo
  centos7:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            private_key_path: test-env/centos7/.vagrant/machines/default/libvirt/private_key
            port: '33311'
      host_settings:
      - use_sudo
  fedora38:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    - systemd-service
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            private_key_path: test-env/fedora38/.vagrant/machines/default/libvirt/private_key
            port: '33341'
      host_settings:
      - use_sudo
  ubuntu2004:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            private_key_path: test-env/ubuntu2004/.vagrant/machines/default/libvirt/private_key
            port: '33331'
