hosts:
  ubuntu2004:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            port: '33331'
            private_key_path: test-env/ubuntu2004/.vagrant/machines/default/libvirt/private_key
  ubuntu2204:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    - systemd-service
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            port: '33332'
            private_key_path: test-env/ubuntu2204/.vagrant/machines/default/libvirt/private_key
      host_settings:
      - use_sudo
  centos7:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            port: '33311'
            private_key_path: test-env/centos7/.vagrant/machines/default/libvirt/private_key
      host_settings:
      - use_sudo
  debian11:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            port: '33303'
            private_key_path: test-env/debian11/.vagrant/machines/default/libvirt/private_key
      host_settings:
      - use_sudo
  centos8:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            private_key_path: test-env/centos8/.vagrant/machines/default/libvirt/private_key
            port: '33312'
  alpine318:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    - systemd-service
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            port: '33351'
            private_key_path: test-env/alpine318/.vagrant/machines/default/libvirt/private_key
      host_settings:
      - use_sudo
  fedora38:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    - systemd-service
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            port: '33341'
            private_key_path: test-env/fedora38/.vagrant/machines/default/libvirt/private_key
      host_settings:
      - use_sudo
