hosts:
  alpine318:
    groups:
    - defaults
    - linux
    - systemd-service
    - docker
    - docker-compose
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            port: '33351'
      host_settings:
      - use_sudo
  fedora38:
    groups:
    - defaults
    - linux
    - systemd-service
    - docker
    - docker-compose
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            port: '33341'
      host_settings:
      - use_sudo
  ubuntu2204:
    groups:
    - defaults
    - linux
    - systemd-service
    - docker
    - docker-compose
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            port: '33332'
      host_settings:
      - use_sudo
  ubuntu2004:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            port: '33331'
            private_key_path: test/ubuntu2004/.vagrant/machines/default/libvirt/private_key
  centos7:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            private_key_path: test/centos7/.vagrant/machines/default/libvirt/private_key
            port: '33311'
      host_settings:
      - use_sudo
  debian11:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            port: '33303'
            private_key_path: test/debian11/.vagrant/machines/default/libvirt/private_key
  centos8:
    groups:
    - defaults
    - docker
    - docker-compose
    - linux
    address: 127.0.0.1
    overrides:
      connectors:
        ssh:
          settings:
            private_key_path: test/centos8/.vagrant/machines/default/libvirt/private_key
            port: '33312'
